blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/RoboFinSystems/robosystems/discussions
    about: For questions or general discussion, start a GitHub Discussion instead
